apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: {{.app}}
    tier: {{.tier}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{.app}}
    tier: {{.tier}}
  name: project-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-projects
        tier: frontend
    spec:
      containers:
      - image: {{.image}}
        # imagePullPolicy: IfNotPresent
        name: news-projects
        ports:
        - containerPort: 80
          protocol: TCP
        # volumeMounts:
        # - mountPath: /usr/src/api/config.js
        #   name: projects-config
        #   subPath: config.js
      terminationGracePeriodSeconds: 30
      # volumes:
      # - name: projects-config
      #   configMap:
      #     name: projects-config
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate