export const STATIUMS_CITY_MAP = [
  { name: '新莊', city: '新北市', },
  { name: '台中', city: '臺中市', },
  { name: '台南', city: '臺南市', },
  { name: '花蓮', city: '花蓮縣', },
  { name: '立德', city: '高雄市', },
  { name: '天母', city: '臺北市', },
  { name: '澄清湖', city: '高雄市', },
  { name: '新竹', city: '新竹市', },
  { name: '屏東', city: '屏東縣', },
  { name: '羅東', city: '宜蘭縣', },
  { name: '斗六', city: '雲林縣', },
  { name: '桃園', city: '桃園市', },
  { name: '嘉義市', city: '嘉義市', },
  { name: '洲際', city: '臺中市', },
]