export default {
  '反空汙': 'Anti-air pollution',
  '反燃煤電廠': 'Anti-coal-fired power plants',
  '反日本核食': 'Anti-nuclear Japanese food',
  '民法一男一女、同婚專法、同婚民法': 'Civil law and a woman, with the special law marriage, marriage with civil law',
  '反性平教育／性平教育': 'Anti-natured education / sex education level',
  '東奧正名': 'Austrian name the East',
  '以核養綠': 'To keep nuclear green',
  '公投': 'Referendum',
  '民進黨': 'DPP',
  '國民黨': 'Kuomintang',
  '地震': 'earthquake',
  '豬瘟': 'Swine fever',
  '颱風': 'typhoon',
  '校長': 'principal',
  '台大': 'National Taiwan University',
  '疫情': 'epidemic',
  '雙城': 'Twins',
  '停電': 'power failure',
  '防疫': 'Epidemic prevention',
  '吳寶春': 'Wu Pao-chun',
  '經濟': 'economic',
  '投資': 'investment',
  '貿易': 'trading',
  '醫療': 'medical',
  '股價': 'share price',
  '兩岸': 'The two sides',
  '環境': 'surroundings',
  '藝術': 'art',
  '觀光': 'go sightseeing',
  '農業': 'agriculture',
  '高雄': 'Kaohsiung',
  '新北': 'New Taipei',
  '宜蘭': 'Ilan',
  '台北': 'Taipei',
  '彰化': 'Changhua',
  '花蓮': 'Hualien',
  '屏東': 'Pingtung',
  '南投': 'Nantou',
  '台南': 'Tainan',
  '台東': 'Taitung',
  '雲林': 'Yunlin',
  '金門': 'Kinmen',
  '基隆': 'Keelung',
  '澎湖': 'Penghu',
  '臺中': 'Taichung',
  '苗栗': 'Miaoli',
  '新竹縣': 'Hsinchu County',
  '新竹市': 'Hsinchu City',
  'None': 'None',
  '桃園': 'Taoyuan',
  '嘉義縣': 'Chiayi County',
  '嘉義市': 'Chiayi City',
  '連江縣': 'Lianjiang County',
  '馬祖': 'Matsu',
  '姚文智': 'Yao Wen-chi',
  '丁守中': 'Ting Shou-chung',
  '李錫錕': 'Lee Si-Kuen',
  '柯文哲': 'Ko Wen-je',
  '吳蕚洋': 'Wu E-yang',
  '蘇貞昌': 'Su Tseng-chang',
  '侯友宜': 'Hou You-yi',
  '鄭文燦': 'Cheng Wen-Tsan',
  '陳學聖': 'Chen Xue-sheng',
  '朱梅雪': 'Zhu Mei-xue',
  '楊麗環': 'Yang Li ring',
  '吳富彤': 'Wufu Tong',
  '林佳龍': 'Lin Chia-lung',
  '盧秀燕': 'Lu Xiuyan',
  '宋原通': 'Song Yuantong',
  '黃偉哲': 'Huang Weizhe',
  '高思博': 'Gao Sibo',
  '林義豐': 'Lin Yifeng',
  '許忠信': 'Xu Zhongxin',
  '蘇煥智': 'Su Huan-chih',
  '陳永和': 'Chen Yonghe',
  '陳其邁': 'Chen Chi-mai',
  '韓國瑜': 'Han Guoyu',
  '蘇盈貴': 'Su Yinggui',
  '璩美鳳': 'Chu Mei-feng',
  '林右昌': 'Lin Yu-chang',
  '謝立功': 'Xie Ligong',
  '林智堅': 'Lin Chih-chien',
  '許明財': 'Hsu Ming-tsai',
  '謝文進': 'Xie Wenjin',
  '黃源甫': 'Huang Yuan Fu',
  '李驥羣': 'Li Yiqun',
  '郭榮睿': 'Guo Rongrui',
  '鄭朝方': 'Zheng Chaofang',
  '楊文科': 'Yang Wenke',
  '徐欣瑩': 'Hsu Xinying',
  '葉芳棟': 'Ye Fangdong',
  '徐耀昌': 'Hsu Yao-chang',
  '徐定禎': 'Hsu Ding Zhen',
  '朱泰平': 'Zhu Taiping',
  '黃玉燕': 'Huang Yuyan',
  '洪國浩': 'Hong Guohao',
  '林明溱': 'Lin Ming-chen',
  '魏明谷': 'Wei Ming-ku',
  '王惠美': 'Wang Huei-mei',
  '洪敏雄': 'Hong Minxiong',
  '黃文玲': 'Huang Wenling',
  '白雅燦': 'Bai Yacan',
  '李進勇': 'Li Jinyong',
  '張麗善': 'Zhang Lishan',
  '林佳瑜': 'Lin Jiayu',
  '王麗萍': 'Wang Liping',
  '涂醒哲': 'Tu Xing-zhe',
  '黃敏惠': 'Huang Ming',
  '蕭淑麗': 'Xiao Shuli',
  '黃宏成台灣阿成世界偉人財神總統': 'Acheng Shi Huang Hongcheng Taiwan industry giants president Fortuna',
  '翁章梁': 'Weng Zhang Liang',
  '吳育仁': 'Wu Yu-jen',
  '林國龍': 'Lin Guo-long',
  '吳芳銘': 'Wu Fang-ming',
  '潘孟安': 'Pan Men-an',
  '蘇清泉': 'Su Qing-quan',
  '李鎔任': 'Li Yuren',
  '陳歐珀': 'Chen Oupo',
  '林姿妙': 'Lin Zimiao',
  '林信華': 'Lin Xinhua',
  '陳秋境': 'Chen Qiujing',
  '林錦坤': 'Lin Jin-kun',
  '劉曉玫': 'Liu Xiaomei',
  '徐榛蔚': 'Xu Zhen Wei',
  '黄師鵬': 'Huang Shih-Peng',
  '劉櫂豪': 'Liu Zhao Hao',
  '饒慶鈴': 'Rao Qingling',
  '彭權國': 'Peng Quanguo',
  '鄺麗貞': 'Kuang Li Zhen',
  '黃裕斌': 'Huang Yubin',
  '陳光復': 'Chen Guangfu',
  '賴峰偉': 'Lai Feng Wei',
  '呂華苑': 'Lu Huayuan ',
  '吳政隆': 'Wu Zheng Long',
  '陳大松': 'Chen Da Song',
  '鄭清發': 'Zheng Qingfa',
  '翁珍聖': 'Weng Zhensheng',
  '劉增應': 'Liu Zengying',
  '蘇柏豪': 'Su Bo Hao',
  '魏耀乾': 'Wei Yaogan',
  '朱秀珍': 'Zhu Xiuzhen',
  '楊鎮浯': 'Yang Zhen Wu',
  '陳福海': 'Chen Fu-hai',
  '謝宜璋': 'Xieyi Zhang',
  '洪志恒': 'Hong Zhiheng',
  '洪和成': 'Hong Hecheng',
  '汪承樺': 'Wang Chenghua',
  '蔡英文': 'Tsai Ing-wen',
  '賴清德': 'Lai Qingde',
  '朱立倫': 'Zhu Lilun',
  '馬英九': 'Ma Ying-jeou',
  '吳敦義': 'Wu Den-yih',
  '陳菊': 'Chen Chu',
  '卓榮泰': 'Cho Jung-tai',
  '陳水扁': 'Chen Shui-bian',
  '顧立雄': 'Guli Xiong',
  '段宜康': 'Duan Yikang',
  '假訊息': 'False message',
  '拚經濟': 'Economic revitalization',
  '兒虐': 'Child abuse',
  '館長': 'curator',
  '朱學恒': 'Chu Hsueh-heng',
  '張善政': 'Chang San-cheng',
  '王炳忠': 'Wangbing Zhong',
  '苗博雅': 'Miao Burson-Marsteller',
  '呂秀蓮': 'Annette Lu',
  '黃國昌': 'Huang Guochang',
  '郭台銘': 'Terry Gou',
  '張亞中': 'Zhang Yazhong',
  '核能減煤': 'Less nuclear energy coal',
  '重啟核四': 'Restart nuclear power plant',
  '鴻海': 'Foxconn',
  '和平協議': 'Peace agreement',
  'Uber': 'Uber',
  '孫安佐': 'Sun Anzuo',
  'NCC': 'NCC',
  '蔡衍明': 'Cai Yanming',
  '酒駕': 'Drunk driving',
  '媽祖': 'Matsu',
  '違章工廠': 'Illegal factories',
  '精神疾病': 'mental illness',
  '台美關係': 'Taiwan-US relations',
  '移民': 'Immigration',
  '呂秋遠': 'Lu Qiuyuan',
  '陸客': 'Mainland tourists',
  '兩岸和平': 'Cross-strait peace',
  '前瞻計畫': 'Forward-looking plan',
  '農業': 'agriculture',
  '環保': 'Environmental protection',
  '勞動': 'labor',
  '勞工': 'laborer',
  '防疫': 'Epidemic prevention',
  '客家': 'Hakka',
  '促轉會': 'Transitional Justice Commission',
  '房價': 'Prices',
  '太陽能': 'Solar',
  '九二共識': '1992 Consensus',
  '天然氣': 'natural gas',
  '國防': 'national defense',
  '風電': 'wind power',
  '污染': 'Pollution',
  '電力': 'electric power',
  '非核': 'Non-nuclear',
  '北漂': 'North drift',
  '主權': 'sovereignty',
  '經濟成長': 'Economic growth',
  '移工': 'Migrante',
  '經濟發展': 'economic development',
  '台獨': 'Taiwan independence',
  '核電廠': 'Nuclear Power Plant',
  '南向': 'To the south',
  '自動化': 'automation',
  '時代力量': 'The era of force',
  '長照': 'Long-term care',
  '年金改革': 'Pension reform'
}