export default {
  '新浪新聞中心': 'Sina News Center',
  '芋傳媒 TaroNews': 'Taro News',
  '聯合新聞網': 'UDN News',
  '中時電子報 CTnews': 'CTnews',
  'NOWnews 今日新聞': 'NOWnews ',
  '無綫新聞': 'TVB News',
  '法廣-法國國際廣播電台': 'Radio France Internationale, RFI',
  '大纪元新闻网': 'Epoch Times News',
  '頭條新聞 | 鉅亨網': 'Anue',
  '自由時報電子報': 'Liberty Times newsletter',
  '新頭殼 Newtalk': 'Newtalk',
  '蘋果日報｜Apple Daily': 'Apple Daily',
  'on.cc東網｜東方報業集團': 'on.cc East Network | Oriental Press Group,',
  'The China Post': 'The China Post',
  'BBC': 'BBC',
  '中央社 CNA': 'CNA',
  'ETtoday新聞雲': 'ETtoday news cloud',
  'ETtoday星光雲': 'ETtoday star Cloud',
  'ETtoday寵物雲': 'ETtoday pet cloud',
  'ETtoday運動雲': 'ETtoday sport cloud',
  'DIGITIMES': 'DIGITIMES',
  '三立新聞網 SETN.com': 'SETN.com',
  'Taiwan News Online': 'Taiwan News Online',
  '上報 Up Media': 'Up Media',
  '妞新聞 niusnews': 'Nius news',
  '電子商務時報．Electronic Commerce Times': 'Electronic Commerce Times',
  '指傳媒 Fingermedia': 'Fingermedia',
  '台灣民眾電子報 | 民眾數位日報': 'Taiwan people Newsletter | populace Digital Daily',
  '自由財經': 'Liberty Times finance',
  '鏡週刊 Mirror Media': 'Mirror Media',
  '眾新聞': 'CitizenNews',
  '台灣數位新聞台/民時新聞Taiwan Digital News': 'Taiwan Digital News',
  '數位時代': 'Business Next',
  'Stand News 立場新聞': 'Stand News',
  'PeoPo 公民新聞': 'PeoPo citizen journalism',
  '新唐人中文电视台在线': 'New Tang Dynasty Television Chinese online',
  '日經中文網': 'Nikkei Chinese',
  '農傳媒': 'Agricultural media',
  '風傳媒 | Storm.mg': 'Storm.mg',
  'The News Lens 關鍵評論網': 'The News Lens',
  'Rti 中央廣播電臺': 'Rti Central Broadcasting Station',
  'ET Fashion': 'ET Fashion',
  'ETtoday遊戲雲': 'ETtoday game cloud',
  'ETtoday健康雲': 'ETtoday health cloud',
  '東森新聞': 'Eastern Broadcasting Co., Ltd.，EBC',
  'TechNews 科技新報': 'TechNews',
  '新公民議會': "The new People's Council",
  '平傳媒 - Fair Media': 'Fair Media',
  '紐約時報中文網 國際縱覽': 'The New York Times Chinese -Traditional ',
  '健康傳媒': 'Health Media',
  'Tnn台灣新聞': 'Tnn Taiwan News',
  'ETtoday 旅遊雲': 'ETtoday tourism clouds',
  'FOCUS TAIWAN': 'FOCUS TAIWAN',
  '市民時報': 'Citizens Times',
  'ETtoday車雲': 'ETtoday car cloud',
  '匯流新聞網': 'Confluence News',
  '上下游News&Market': 'News&Market',
  '放言Fount Media': 'Fount Media',
  '民報 Taiwan People News': 'Taiwan People News',
  '壹電視 NextTV': 'NextTV',
  '朝日新聞中文網': 'Asahi Shimbun Chinese',
  '報導者 The Reporter': 'The Reporter',
  '一零一傳媒': 'One hundred and one media',
  'Global Voices 繁體中文': 'Global Voices Traditional Chinese,',
  '台灣新聞網': 'Taiwan News Network',
  '生命力新聞': 'Vitality News',
  '中華日報新聞網': 'China Daily News',
  '主流傳媒': 'Mainstream media',
  '天下雜誌': 'Commonwealth Magazine',
  '台視全球資訊網': 'TTV WWW',
  '沃草國會無雙': 'Watchout',
  'ETtoday房產雲': 'ETtoday estate cloud',
  '自立晚報 -  ': 'Independence Evening Post',
  '中時電子報 CTnews - Chinatimes.com': 'CTnews - Chinatimes.com',
  '信傳媒': 'Credere Media',
  'CTnews書刊': 'CTnews books',
  '快點TV - 中時電子報': 'Chinatimes TV',
  'CTnews新聞專輯': 'CTnews album',
  '華視全球資訊網': 'CTS WWW',
  '今日導報 Herald-Today': 'Herald-Today',
  '中國廣播公司全球資訊網': 'China Broadcasting Corporation WWW,',
  '前衛即時新聞 AGTV NEWS': '',
  'The Liberty News - 自由新聞報新聞網': 'The Liberty News',
  '中天電視': 'CTI Television Inc.',
  '臺灣時報': 'Taiwan Times,',
  'on.cc東網': 'on.cc',
  'USTV 非凡電視台': 'USTV',
  '自由體育': 'Liberty Times sport',
  '自由娛樂': 'Liberty Times entertainment',
  'tvb.com': 'tvb.com',
  '公視新聞網': 'PTV News',
  '自由評論網 自由電子報 ': 'Liberty Times commentary',
  'CommonWealth Magazine': 'CommonWealth Magazine',
  'PNN公視新聞議題中心': 'PNN public television news topic centers',
  '鷹傳媒電子報': 'Eagle Media Newsletter',
  '九八新聞台': 'Ninety-eight News',
  '原傳媒 | 台灣原住民族電子報': 'Original Media | Taiwan Aboriginal newsletter',
  '台灣新生報': 'Taiwan Shin Sheng Daily News',
  '獨立媒體': 'Independent media',
  '壹傳媒 | Next Digital': 'Next Digital',
  'Taiwan Today': 'Taiwan Today',
  'TVBS官方網站': 'TVBS official website',
  '欣傳媒XinMedia': 'XinMedia',
  'PanMedia 泛科知識': 'PanMedia',
  '0media': '0media',
  '明報新聞網': 'Ming Pao Daily News',
  '新傳媒股份有限公司': 'New Media Co., Ltd.'
}