export const CITIES = {
  TAIPEI: 'TAIPEI',
  TAOYUAN: 'TAOYUAN',
  NEWTAIPEI: 'NEWTAIPEI',
  TAICHUNG: 'TAICHUNG',
  TAINAN: 'TAINAN',
  KAOHSIUNG: 'KAOHSIUNG',
}
export const INFOGRAPH_AXIS = {
  X: 'rent',
  y: 'unit',
}
const VIEW_SIZE = {
  S: {
    WIDTH: 400,
    HEIGHT: 300,
  },
  L: {
    WIDTH: 665,
    HEIGHT: 420,
  },
}
export const TIPS = {
  'FLOOR': 'floor',
  'UNIT': 'unit',
  'OBJ_TYPE': 'obj_type',
  'LIVING_ROOMS': 'living_rooms',
  'RENT': 'rent',
  'WATER': 'water_fee',
  'GAS': 'gas_fee',
  'INTERNET': 'internet_fee',
  'POWER': 'electricity_fee',
  'WIRE': 'tv_fee',
  'BED': 'is_offer_bed',
  'TV': 'is_offer_tv',
  'AIR_CONDITIONER': 'is_offer_aircon',
  'SOFA': 'is_offer_sofa',
  'FRIGE': 'is_offer_frige',
}
export const GEARS = {
  'POSITION': {
    'OPTIONS': {
      'TAIPEI': 17,
      'NEWTAIPEI': 11,
      'TAOYUAN': 14,
      'TAICHUNG': 16,
      'TAINAN': 18,
      'KAOHSIUNG': 25,
    },
  },
  // 'BUDGET': {
  //   'OPTIONS': {
  //     '6K_DOWN': [ 0, 6, ],
  //     '6K_TO_10K': [ 7, 10, ],
  //     '10K_TO_15K': [ 11, 15, ],
  //     '15K_TO_20K': [ 16, 20, ],
  //     '20K_TO_25K': [ 21, 25, ],
  //     '25K_TO_30K': [ 26, 30, ],
  //     '30K_UP': [ 31, ],
  //   },
  // },
  // 'SIZE': {
  //   'OPTIONS': {
  //     '5_DOWN': [ 0, 5, ],
  //     '5_TO_10': [ 6, 10, ],
  //     '10_TO_15': [ 11, 15, ],
  //     '15_TO_20': [ 16, 20, ],
  //     '20_UP': [ 21, ],
  //   },
  // },
  'TYPE': {
    'OPTIONS': {
      'YA': 3,
      'TAO': 1,
      'SHARE_TAO': 2,
      'HOUSEHOLD': 0,
    },
  },
  'ROLE': {
    'OPTIONS': {
      'STUDENT': 'student',
      'DAILY_WORKER': 'daily_worker',
      'FAMILY': 'family',
    },
  },
  'OTHER': {
    isMulti: true,
    'OPTIONS': {
      'PET_NEEDED': 'is_pettable',
      'COOK_NEEDED': 'is_cookable',
    },
  },  
}
export const PROGRAM_TYPE = {
  STRING: 'STRING',
  GRAPH: 'GRAPH',
}
export const PROGRAM = [
  { id: '1', type: 'STRING', isExplanation: false, },
  { 
    id: '2', 
    type: 'GRAPH',
    filters: {
      POSITION: 'TAOYUAN',
      POGRAM_BUDGET: null,
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,
    },
    graph: '/proj-assets/rent/program-1.png',
    graphMB: '/proj-assets/rent/program-mobile-1.png',
    subinfo: [
      { city: 'TAIPEI', feature: '1500' },
      { city: 'NEWTAIPEI', feature: '1000' },
      { city: 'TAICHUNG', feature: '813' },
      { city: 'TAINAN', feature: '717' },
      { city: 'KAOHSIUNG', feature: '725' },
    ],
  },
  { id: '3',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: null,
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,
    },
    graph: '/proj-assets/rent/program-2.png',
    graphMB: '/proj-assets/rent/program-mobile-2.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '12000' },
      { city: 'TAOYUAN', feature: '10000' },
      { city: 'TAICHUNG', feature: '8499' },
      { city: 'TAINAN', feature: '6000' },
      { city: 'KAOHSIUNG', feature: '7000' },
    ],
  },
  { id: '4',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: null,
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,
    },
    graph: '/proj-assets/rent/program-2.png',
    graphMB: '/proj-assets/rent/program-mobile-2.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '24%' },
      { city: 'TAOYUAN', feature: '18%' },
      { city: 'TAICHUNG', feature: '17%' },
      { city: 'KAOHSIUNG', feature: '14%' },
      { city: 'TAINAN', feature: '12%' },
    ],
  },
  { id: '5', type: 'STRING', isExplanation: true, },
  { id: '6',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,
    },
    graph: '/proj-assets/rent/program-4.png',
    graphMB: '/proj-assets/rent/program-mobile-4.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '14%' },
      { city: 'TAOYUAN', feature: '29%' },
      { city: 'TAICHUNG', feature: '29%' },
      { city: 'KAOHSIUNG', feature: '47%' },
      { city: 'TAINAN', feature: '58%' },
    ],
  },
  { id: '7', type: 'STRING', isExplanation: true, },
  { id: '8',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: 3,
      OTHER: null,
    },
    graph: '/proj-assets/rent/program-5.png',
    graphMB: '/proj-assets/rent/program-mobile-5.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '37%' },
      { city: 'TAOYUAN', feature: '65%' },
      { city: 'TAICHUNG', feature: '85%' },
      { city: 'TAINAN', feature: '72%' },
      { city: 'KAOHSIUNG', feature: '57%' },
    ],
    stamp: [
      { name: 'SHARE_TAO', type: 'black', },
      { name: 'INDEPANDENT_TAO', type: 'white', },
      { name: 'INDEPANDENT_TAO', type: 'white', },
      { name: 'INDEPANDENT_TAO', type: 'white', },
      { name: 'INDEPANDENT_TAO', type: 'white', },
    ],
  },
  { id: '9', type: 'STRING', isExplanation: true, },
  { id: '10',
    type: 'GRAPH',
    filters: {
      POSITION: 'NEWTAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      PROGRAM_GENDER: null,
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: [ 'is_pettable' ],
    },
    graph: '/proj-assets/rent/program-6.png',
    graphMB: '/proj-assets/rent/program-mobile-6.png',
    subinfo: [
      { city: 'TAIPEI', feature: '10%' },
      { city: 'TAOYUAN', feature: '11%' },
      { city: 'TAICHUNG', feature: '11%' },
      { city: 'TAINAN', feature: '14%' },
      { city: 'KAOHSIUNG', feature: '16%' },
    ],
  },
  { id: '11', type: 'STRING', isExplanation: true, },
  { id: '12',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      PROGRAM_GENDER: 'female',
      POGRAM_FLOOR: null,      
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,      
    },  
    graph: '/proj-assets/rent/program-7.png',
    graphMB: '/proj-assets/rent/program-mobile-7.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '17%' },
      { city: 'KAOHSIUNG', feature: '16%' },
      { city: 'TAINAN', feature: '10%' },
      { city: 'TAOYUAN', feature: '4%' },
      { city: 'TAICHUNG', feature: '8%' },
    ],
  },
  { id: '13', type: 'STRING', isExplanation: true, },
  { id: '14',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      POGRAM_FLOOR: -1,
      PROGRAM_GENDER: null,
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,       
    },    
    graph: '/proj-assets/rent/program-8.png',
    graphMB: '/proj-assets/rent/program-mobile-8.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '6%' },
      { city: 'TAICHUNG', feature: '0.6%' },
      { city: 'TAINAN', feature: '0.6%' },
      { city: 'KAOHSIUNG', feature: '0.6%' },
      { city: 'TAOYUAN', feature: '0.5%' },
    ],
  },
  { id: '15', type: 'STRING', isExplanation: true, },
  { id: '16',
    type: 'GRAPH',
    filters: {
      POSITION: 'TAIPEI',
      POGRAM_BUDGET: 'less-than-6600',
      POGRAM_FLOOR: 0,
      PROGRAM_GENDER: null,
      PROGRAM_NULL: null,
      TYPE: null,
      OTHER: null,       
    },   
    graph: '/proj-assets/rent/program-9.png',
    graphMB: '/proj-assets/rent/program-mobile-9.png',
    subinfo: [
      { city: 'NEWTAIPEI', feature: '36%' },
      { city: 'TAINAN', feature: '28％' },
      { city: 'KAOHSIUNG', feature: '27%%' },
      { city: 'TAOYUAN', feature: '26%' },
      { city: 'TAICHUNG', feature: '20%' },
    ],
  },
  { id: '17', type: 'STRING', isExplanation: true, },
  { id: '18', type: 'GRAPH',
    filters: {
      POSITION: '',
      POGRAM_BUDGET: null,
      POGRAM_FLOOR: null,
      PROGRAM_GENDER: null,
      PROGRAM_NULL: true,
      TYPE: null,
      OTHER: null, 
    },
    graph: '/proj-assets/rent/question.jpg',
    graphMB: '/proj-assets/rent/question.jpg',
    last: true,
  },
  { id: '19', type: 'STRING', isExplanation: true, },
  { id: '20', type: 'STRING', isExplanation: false, },
]